### PR TITLE
Get card from customer if card not specified on new charge

### PR DESCRIPTION
**Pull request by JakovlevDS**

### CODE REVIEW

**Comment by alexmamonchik** [comment]
@JakovlevDS thanks for contribution. Did you run your test in `live` mode? Please, check https://github.com/rebelidealist/stripe-ruby-mock#live-testing

**Comment by JakovlevDS** [comment]
@alexmamonchik yes, I did. It looks good.
screenshot 2016-05-05 14 18 04

**Comment by alexmamonchik** [comment]
@JakovlevDS cool! Can you add prefix `live` to your test and update PR? like [here](https://github.com/JakovlevDS/stripe-ruby-mock/blob/fix/charge-source-from-customer/spec/shared_stripe_examples/charge_examples.rb#L5)

**Comment by JakovlevDS** [comment]
@alexmamonchik done. not sure why CI build has failed

**Comment by kylefox** [comment]
Hello, just wondering what the status is on this 😀  I came across the bug described in #199 as well. Happy to help if I can!

**Pull request merged**
