### PR TITLE
allow for updating an application fee upon charge capture

### PR DESCRIPTION
**Pull request by ehsanul**

### CODE REVIEW

**Comment by ehsanul** [comment]
Looks like spurious test failures to me. Is there a way to retry the travis CI build?

**Comment by ehsanul** [comment]
@alexmamonchik Not sure if you're the right person, but looks like these specs are failing on master currently.

**Comment by alexmamonchik** [comment]
hi @ehsanul For restart Travis just close and open this PR. Yes, I see failed tests:
```shell
Failures:

  1) StripeMock::Instance behaves like Charge API disallows most parameters on updating a stripe charge

     Failure/Error: expect { charge.save }.to raise_error(Stripe::InvalidRequestError, /Received unknown parameters: currency, amount, source/i)

       expected Stripe::InvalidRequestError with message matching /Received unknown parameters: currency, amount, source/i, got #<Stripe::InvalidRequestError: (Status 400) Received unknown parameters: amount, currency, source> with backtrace:

         # ./lib/stripe_mock/request_handlers/charges.rb:44:in `update_charge'

         # ./lib/stripe_mock/instance.rb:92:in `mock_request'

         # ./lib/stripe_mock/api/instance.rb:22:in `call'

         # ./lib/stripe_mock/api/instance.rb:22:in `block in alias_stripe_method'

         # /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/stripe-1.38.0/lib/stripe/api_operations/request.rb:15:in `request'

         # /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/stripe-1.38.0/lib/stripe/api_operations/request.rb:37:in `request'

         # /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/stripe-1.38.0/lib/stripe/api_operations/update.rb:35:in `save'

         # ./spec/shared_stripe_examples/charge_examples.rb:202:in `block (3 levels) in <top (required)>'

         # ./spec/shared_stripe_examples/charge_examples.rb:202:in `block (2 levels) in <top (required)>'

     Shared Example Group: "Charge API" called from ./spec/support/stripe_examples.rb:12

     # ./spec/shared_stripe_examples/charge_examples.rb:202:in `block (2 levels) in <top (required)>'

  2) StripeMock::Instance behaves like Customer API updates a stripe customer's card from a hash

     Failure/Error: expect(original.default_source).to_not eq(card.id)

       

       expected: value != "test_cc_2"

            got: "test_cc_2"

       

       (compared using ==)

     Shared Example Group: "Customer API" called from ./spec/support/stripe_examples.rb:14

     # ./spec/shared_stripe_examples/customer_examples.rb:318:in `block (2 levels) in <top (required)>'

  3) StripeMock Server behaves like Charge API disallows most parameters on updating a stripe charge

     Failure/Error: expect { charge.save }.to raise_error(Stripe::InvalidRequestError, /Received unknown parameters: currency, amount, source/i)

       expected Stripe::InvalidRequestError with message matching /Received unknown parameters: currency, amount, source/i, got #<Stripe::InvalidRequestError: (Status 400) Received unknown parameters: amount, currency, source> with backtrace:

         # ./lib/stripe_mock/client.rb:20:in `block (2 levels) in mock_request'

         # ./lib/stripe_mock/client.rb:17:in `tap'

         # ./lib/stripe_mock/client.rb:17:in `block in mock_request'

         # ./lib/stripe_mock/client.rb:86:in `timeout_wrap'

         # ./lib/stripe_mock/client.rb:16:in `mock_request'

         # ./lib/stripe_mock/api/client.rb:35:in `redirect_to_mock_server'

         # ./lib/stripe_mock/api/instance.rb:22:in `call'

         # ./lib/stripe_mock/api/instance.rb:22:in `block in alias_stripe_method'

         # /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/stripe-1.38.0/lib/stripe/api_operations/request.rb:15:in `request'

         # /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/stripe-1.38.0/lib/stripe/api_operations/request.rb:37:in `request'

         # /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/stripe-1.38.0/lib/stripe/api_operations/update.rb:35:in `save'

         # ./spec/shared_stripe_examples/charge_examples.rb:202:in `block (3 levels) in <top (required)>'

         # ./spec/shared_stripe_examples/charge_examples.rb:202:in `block (2 levels) in <top (required)>'

     Shared Example Group: "Charge API" called from ./spec/support/stripe_examples.rb:12

     # ./spec/shared_stripe_examples/charge_examples.rb:202:in `block (2 levels) in <top (required)>'

  4) StripeMock Server behaves like Customer API updates a stripe customer's card from a hash

     Failure/Error: expect(original.default_source).to_not eq(card.id)

       

       expected: value != "test_cc_2"

            got: "test_cc_2"

       

       (compared using ==)

     Shared Example Group: "Customer API" called from ./spec/support/stripe_examples.rb:14

     # ./spec/shared_stripe_examples/customer_examples.rb:318:in `block (2 levels) in <top (required)>'
```

**Comment by ehsanul** [comment]
@alexmamonchik thanks. Those specs are failing for me on master though, so I'm pretty sure it's unrelated to this PR.

**Comment by alexmamonchik** [comment]
I see the problem: it happens when use stripe >= 1.38

**Comment by alexmamonchik** [comment]
I have opened issue https://github.com/stripe/stripe-ruby/issues/406

**Comment by ehsanul** [comment]
@alexmamonchik Alright, looks like we have a passing build finally, thanks for your help. Good to merge?

**Pull request merged**
