### PR TITLE
Implement saving already existing Charges

### PR DESCRIPTION
**Pull request by ccahoon**
Hello, I've implemented mock updating charges. I've tested it with the "live" server (very handy!). I'm open to suggestions for improvement.

### CODE REVIEW

**Comment by mindeavor** [comment]
I updated the circle ci testing, please rebase with master.

**Comment by ccahoon** [comment]
I rebased with master-- it looks like the same build failure is happening.

**Comment by mindeavor** [comment]
Come on, travis...

**Comment by mindeavor** [comment]
Can you try closing this PR and creating a new one? I think that might make TravisCI happy.

**Comment by mindeavor** [comment]
To be clear, I mean recreate this PR with the same commits.

**Comment by ccahoon** [comment]
closing this one

**Pull request closed without merging**
