### PR TITLE
Expand balance_transaction when creating charges

### PR DESCRIPTION
**Pull request by mikker**
I'm not sure how to test this but FWIW it works.

### CODE REVIEW

**Comment by alexmamonchik** [comment]
can you describe how you work with it? I can't find in doc any info about `expand` param.

**Comment by mikker** [comment]
Sure, the relevant part of the docs is this: https://stripe.com/docs/api/ruby#expanding_objects

I use it to get Stripe's fees right away when I charge.

```ruby
charge = Stripe::Charge.create({
  # ...
  amount: 30,
  expand: ['balance_transaction']
})

puts charge.balance_transaction.fee #=> 2.22 or whatever
```

**Comment by mikker** [comment]
The implementation is of course pretty naive right now, as it _only_ works with this single case. In principle it ought to work with every request. That's a bigger undertaking.

**Comment by mikker** [comment]
@alexmamonchik Do you need any further explanation? Glad to help.

**Comment by alexmamonchik** [comment]
@mikker no, thanks. Looks good for me. But can you add test for your changes?

**Comment by mikker** [comment]
@alexmamonchik Sure – how does this look?

**Comment by alexmamonchik** [comment]
thanks!

**Comment by mikker** [comment]
Thank you!

**Pull request merged**
