### PR TITLE
Add support for PaymentIntents

### PR DESCRIPTION
**Pull request by ashkan18**
# Change
Add Basic Support for [`PaymentIntents` API](https://stripe.com/docs/api/payment_intents) following [contribution doc](https://github.com/rebelidealist/stripe-ruby-mock/wiki/Implementing-a-New-Behavior#contributing-to-stripemock)

Fixes https://github.com/rebelidealist/stripe-ruby-mock/issues/618

# Different Statuses
As part of test you may want to get payment intents in `succeeded`, `requires_action` or `requires_payment_method` states. In this current approach when creating a `PaymentIntent` by default you'll get `succeeded` payment intent. 
- setting amount to `3184` (which comes from last 4 digits of Stripe's test card for SCA in [here](https://stripe.com/docs/testing#regulatory-cards)) will set the state to `requires_action`
- setting amount to `3178` (coming from same link above) will pass authentication but fail payment method and set the status to `requires_payment_method`. In this case we also set `last_payment_error` on `PaymentIntent` to a simple `card_declined` error.

### CODE REVIEW

**Comment by ashkan18** [comment]
Looks like failures are not related to my changes and happen only on _live_ tests, right?

**Comment by sofianeOuafir** [comment]
what version include your changes @ashkan18 ?

**Comment by ashkan18** [comment]
@sofianeOuafir i think it got released as part of `2.5.8`

**Comment by sofianeOuafir** [comment]
@ashkan18 I have the 2.5.8 but your changes don't seem to be a part of it. For instance, the mock_payment_intent method is not in the stripe-ruby-mock/lib/stripe_mock/data.rb file

**Comment by sofianeOuafir** [comment]
@ashkan18 btw, thanks for you work :) Do you know how can I solve my problem?

**Comment by ashkan18** [comment]
sure! @sofianeOuafir what do you have in your `Gemfile`? we have switched to that and things are working fine for us.

**Comment by olimart** [comment]
@ashkan18 
Thanks for your work. I'm running into the situation where when we confirm the payment intent, Stripe attaches any successful charges to the `PaymentIntent` object.
We rely on status (which becomes `succeeded`) but would also like to make sure charge is included.
Would be great to include that case as well, don't you think?

**Pull request merged**
