### PR TITLE
Update to 1.43

### PR DESCRIPTION
**Pull request by adbjesus**
Deals with issue #335 

I guess we should bump the version. But i am not sure if it should be to 2.2.5 or 2.3.0. So I will wait for feedback before doing that.

### CODE REVIEW

**Comment by adbjesus** [comment]
@typeoneerror Tagging you here since you said you'd be happy to review it on the issue :P

**Comment by typeoneerror** [comment]
Looks great at first glance. I'm going to pull it down tomorrow and run it against a few applications I'm using stripe-ruby-mock in. Keep ya posted.

One question: does Stripe 1.43 completely remove the subscriptions endpoint on customer? Not sure if we need to be backwards compatible at all.

**Comment by adbjesus** [comment]
The only one that seems to keep working is `get /v1/customers/(.*)/subscriptions/(.*)` Through  something like `customers.subscriptions.retrieve(subscription_id)` but they don't seem to reference it on the API docs anymore.

**Comment by adbjesus** [comment]
Actually I went back to check and all of these:

* `get /v1/customers/(.*)/subscriptions` -> `customer_object.subscritpions.all()`
* `post /v1/customers/(.*)/subscriptions` ->  `customer_object.subscriptions.create(options)`
* `get /v1/customers/(.*)/subscriptions/(.*)` -> `customer_object.subscriptions.retrieve(subscription_id)`

still seem to work. Even though they are not mentioned in the docs. Do you want to keep these routes?

**Comment by mysmallidea** [comment]
I've run several tests using this on my end, and it all looks pretty solid. I've run tests with with: 
* Stripe::Subscription.all
* Stripe::Subscription.retrieve
* Stripe::Subscription.save

**Comment by alexmamonchik** [comment]
so, @adbjesus thank you, great job! Merged! Create one more PR for any future updates.
@mindeavor Please, release gem `2.3.0` I think

**Comment by brianlittmann** [comment]
Good stuff. One thing to note though, whenever the `stripe-ruby` gem gets a minor version bump such as 1.43.1 (as of June 17), the dependency check will fail.

**Comment by pedantic-git** [comment]
Here's a simple spec that illustrates the issue (this is using `stripe` 1.50.0 and `stripe-ruby-mock` 2.3.1):

```ruby
  describe 'stripe test' do
    it 'works with the latest stripe-ruby-mock gem' do
      token = StripeMock.create_test_helper.generate_card_token
      cus   = Stripe::Customer.create(source: token)
      expect {
        cus.update_subscription(plan: 'default')
      }.not_to raise_error
    end
  end
```

```
Failures:

  1) Subscription stripe test works with the latest stripe-ruby-mock gem
     Failure/Error:
       expect {
         cus.update_subscription(plan: 'default')
       }.not_to raise_error
     
       expected no Exception, got #<Stripe::InvalidRequestError: (Status 404) No such customer: test_cus_3/subscription> with backtrace:
         # /bundle/gems/stripe-ruby-mock-2.3.1/lib/stripe_mock/instance.rb:117:in `assert_existence'
         # /bundle/gems/stripe-ruby-mock-2.3.1/lib/stripe_mock/request_handlers/customers.rb:61:in `update_customer'
         # /bundle/gems/stripe-ruby-mock-2.3.1/lib/stripe_mock/instance.rb:96:in `mock_request'
         # /bundle/gems/stripe-ruby-mock-2.3.1/lib/stripe_mock/api/instance.rb:22:in `call'
         # /bundle/gems/stripe-ruby-mock-2.3.1/lib/stripe_mock/api/instance.rb:22:in `block in alias_stripe_method'
         # /bundle/gems/stripe-1.50.0/lib/stripe/api_operations/request.rb:15:in `request'
         # /bundle/gems/stripe-1.50.0/lib/stripe/api_operations/request.rb:37:in `request'
         # /bundle/gems/stripe-1.50.0/lib/stripe/customer.rb:62:in `update_subscription'
[snip]
```

With my changes, this spec doesn't fail. Does it work for you? I did have `Stripe.api_version = '2015-02-16'` but even with this commented out I get the same failure.

Thanks for your help!

**Pull request merged**
