### PR TITLE
Expand balance transaction when retrieving an existing charge

### PR DESCRIPTION
**Pull request by vkinelev**
- `Stripe::Charge.retrieve` includes balance transaction object if `expand: ['balance_transaction']` has been passed into params. 
- Added spec

### CODE REVIEW

**Comment by vkinelev** [comment]
I'm trying to understand why Travis build fails. I haven't touched that code:

```
StripeMock::Instance behaves like Coupon API retrieve coupon cannot retrieve a stripe coupon that doesn't exist
     Failure/Error: expect { Stripe::Coupon.retrieve('nope') }.to raise_error {|e|
       
       expected: "id"
            got: "coupon"
       
       (compared using ==)
     Shared Example Group: "Coupon API" called from ./spec/support/stripe_examples.rb:15
     # ./spec/shared_stripe_examples/coupon_examples.rb:57:in `block (3 levels) in <top (required)>'
```

A spec is:

```ruby
    it "cannot retrieve a stripe coupon that doesn't exist" do
      expect { Stripe::Coupon.retrieve('nope') }.to raise_error {|e|
        expect(e).to be_a Stripe::InvalidRequestError
        expect(e.param).to eq('id')
        expect(e.http_status).to eq(404)
      }
    end
```

Live Stripe returns "coupon" type in InvalidRequestError, but mock server returns "id":
```ruby
      def get_coupon(route, method_url, params, headers)
        route =~ method_url
        assert_existence :id, $1, coupons[$1]
      end
```

I probably have to setup live testing locally :)

**Comment by vkinelev** [comment]
I got the same error when I run tests locally. It happens both in my branch and commit tagged with "v2.4.0".

A hint would be so much appreciated! :)

**Comment by psusmars** [comment]
I also received a similar response from Travis when submitting a pull request that had nothing to do with the coupon code.

**Comment by alexmamonchik** [comment]
please, pull master into your branch

**Comment by vkinelev** [comment]
@alexmamonchik done!

**Pull request merged**
