### PR TITLE
Webhook events: Add billing Items to the subscription

### PR DESCRIPTION
**Pull request by amrdruid**
## Conext: 

Subscription now can have multiple plans in `items`

This PR referes to this open issue #429

### CODE REVIEW

**Comment by alexmamonchik** [comment]
thank you very much! Can you add a test for your changes?

**Comment by amrdruid** [comment]
@alexmamonchik Sure thing, there's other place that I need to apply this change, it should be ready by tomorrow :+1:

**Comment by alexmamonchik** [comment]
Hi @amrdruid Any progress with test? Thank you

**Comment by amrdruid** [comment]
@alexmamonchik I was super busy in the last days, there some other changes that I want to push to make everything in Sync and I will write the tests for them.

Maybe it will be available this weekend, sorry for not finalizing this sooner

**Comment by alexmamonchik** [comment]
please, pull master. It fixed travis issue.

**Comment by mattfordham** [comment]
Are there plans to merge this in soon?

**Comment by alexmamonchik** [comment]
@mattfordham I'm waiting for confirmation test that Druid's code really changed anything.

**Comment by amrdruid** [comment]
@mattfordham @alexmamonchik 

I am working today on this guys, I have been using this version to test a functionality I have implemented and it's all going well, What I will do today and the weekend is to add the tests for this modification and change some other parts the change of having more than 1 plan for one subscription 

I know this took some more than expected, I hope it's sorted out this weekend

**Comment by mattfordham** [comment]
@amrdruid Is the intent of this PR to fully support a Subscription having "items", as opposed to a "plan"? I ask because it seems changes would need to be made to the [Subscriptions request handler](https://github.com/rebelidealist/stripe-ruby-mock/blob/master/lib/stripe_mock/request_handlers/subscriptions.rb#L35) as well. Thanks!

**Comment by amrdruid** [comment]
@mattfordham Yea, this PR hopefully will fully support the subscription having `items`

Thanks for the tip, I will have a look, let me know if there's other places that I need to give a look for

**Comment by amrdruid** [comment]
@alexmamonchik @mattfordham 

If you guys can kindly review and give me your feedback

**Comment by mattfordham** [comment]
@amrdruid What about actually creating Subscriptions with "items" via the API, like this: https://github.com/rebelidealist/stripe-ruby-mock/issues/429#issuecomment-320040935. I don't think you're PR addresses that side of things? @alexmamonchik am I correct?

**Comment by amrdruid** [comment]
@mattfordham This PR solves adds the billing items to the Webhook events, I can create another PR for the mocking of the creation of the Subscription with the new format after this one

**Pull request merged**
