### PR TITLE
Trial end fix with tests

### PR DESCRIPTION
**Pull request by evanmightybell**
This is wrap up for the pull request from @ryangrush. See https://github.com/rebelidealist/stripe-ruby-mock/pull/455

I resolved the merge conflicts and added a test for his fix.

### CODE REVIEW

**Comment by evanmightybell** [comment]
@alexmamonchik My organization uses this great gem. Unfortunately, we just implemented features where we need support for products and SKUs on Stripe. So I need to get three PRs across the finish line.

1. This one (which hopefully finishes https://github.com/rebelidealist/stripe-ruby-mock/pull/455)
2. This one, which I think is the best one for supporting products: https://github.com/rebelidealist/stripe-ruby-mock/pull/536
3. And there isn't one for SKUs yet, but I am going to try to write one today.

Any help or guidance from you, in terms of what you are looking for, would be much appreciated.

**Comment by evanmightybell** [comment]
It looks like there are CI failures on the master branch, but this branch doesn't add any new failures.

**Comment by alexmamonchik** [comment]
@evanmightybell I'm not alone works on this. But I don't have enough time for that project. Please, contact @gilbert and ask him for push rights.

**Comment by evanmightybell** [comment]
@gilbert Any chance we can look into getting this merged?

**Comment by gilbert** [comment]
@evanmightybell I haven't coded ruby in a while now. Would you like to become a contributor?

**Comment by evanmightybell** [comment]
@gilbert I would love to become a contributor!

**Comment by gilbert** [comment]
Invite sent!

**Pull request merged**
