### PR TITLE
Create a new charge each time an invoice is paid

### PR DESCRIPTION
**Pull request by justin-rhoades**
* addresses issue #403 

* previously, the Invoices#pay_invoice method hard coded a charge id,
this change creates a dynamic charge object each time the method is
called.

* if there is not a customer associated with the invoice, it creates an
anonymous charge by using the generate_card_token helper

* if there is a customer associated with the invoice, it will create a
charge using the customers default payment method, the same behavior
stripe implements

### CODE REVIEW

**Comment by alexmamonchik** [comment]
👍

**Comment by alexmamonchik** [comment]
please, pull master into your branch

**Comment by justin-rhoades** [comment]
Gotcha, sorry - missed that last commit

**Comment by typeoneerror** [comment]
Great work, @justin-rhoades! Thanks for fixing and closing my issue.

**Pull request merged**
