### PR TITLE
Adds support for customer coupons.

### LINKED ISSUE #72: Stripe::Customer.create with a coupon does not return a discount
Currently when a `Stripe::Customer` is created with a `coupon` attribute, a discount is not created and returned with the customer response. Instead, a `coupon` property is returned, but this does not match Stripe's live response.

Example:

```ruby
coupon = 'stripe_4_lyfe'

Stripe::Coupon.create(
  percent_off: 25,
  duration: 'repeating',
  duration_in_months: 3,
  id: coupon
)

customer_card = {
  number: 4242424242424242,
  exp_month: 2,
  exp_year: Time.now.year.next,
  cvc: "314"
}

Stripe::Customer.create(card: customer_card, coupon: coupon)
```

With the mock server running:

```json
{
  "id": "test_cus_5",
  "email": "stripe_mock@example.com",
  "description": "an auto-generated stripe customer data mock",
  "object": "customer",
  "created": 1372126710,
  "livemode": false,
  "delinquent": false,
  "discount": null,
  "account_balance": 0,
  "cards": {"object":"list","count":1,"url":"/v1/customers/test_cus_5/cards","data":[{"id":"test_cc_6","object":"card","last4":"4242","type":"Visa","exp_month":4,"exp_year":2016,"fingerprint":"wXWJT135mEK107G8","customer":"test_cus_5","country":"US","name":"Johnny App","address_line1":null,"address_line2":null,"address_city":null,"address_state":null,"address_zip":null,"address_country":null,"cvc_check":null,"address_line1_check":null,"address_zip_check":null}]},
  "default_card": "test_cc_6",
  "coupon": "stripe_4_lyfe",
  "subscriptions": {"data":[],"count":0,"object":"list","url":"/v1/customers/test_cus_5/subscriptions"}
}
```

Without the mock server running:

```json
{
  "id": "cus_3d82VayotGv2d6",
  "object": "customer",
  "created": 1394313303,
  "livemode": false,
  "description": null,
  "email": null,
  "delinquent": false,
  "metadata": {},
  "subscriptions": {"object":"list","count":0,"url":"/v1/customers/cus_3d82VayotGv2d6/subscriptions","data":[]},
  "discount": {"coupon":{"id":"stripe_4_lyfe","created":1394313289,"percent_off":25,"amount_off":null,"currency":null,"object":"coupon","livemode":false,"duration":"repeating","redeem_by":null,"max_redemptions":null,"times_redeemed":1,"duration_in_months":3,"valid":true,"metadata":{}},"start":1394313303,"object":"discount","customer":"cus_3d82VayotGv2d6","subscription":null,"end":1402262103},
  "account_balance": 0,
  "currency": null,
  "cards": {"object":"list","count":1,"url":"/v1/customers/cus_3d82VayotGv2d6/cards","data":[{"id":"card_103d82237mKPGzkIw2wcCYex","object":"card","last4":"4242","type":"Visa","exp_month":2,"exp_year":2015,"fingerprint":"BvtkZuO7Uuz75a75","customer":"cus_3d82VayotGv2d6","country":"US","name":null,"address_line1":null,"address_line2":null,"address_city":null,"address_state":null,"address_zip":null,"address_country":null,"cvc_check":"pass","address_line1_check":null,"address_zip_check":null}]},
  "default_card": "card_103d82237mKPGzkIw2wcCYex"
}
```

This is useful to have when testing that a coupon properly converts into a discount for the stripe customer. In my case, it's an integration test that wants to assert the presence of the discount after a user submitted a form with a valid stripe token and coupon.

### PR DESCRIPTION
**Pull request by jrmyward**
* This is mostly borrowed from #74
* Fixes #72

### CODE REVIEW

**Comment by alexmamonchik** [comment]
I'm waiting this fixes. Please, apply it.

**Comment by mindeavor** [comment]
The first test you wrote doesn't pass against Stripe's live servers. It returns this error:

```
StripeMock::Instance behaves like Customer API creates a customer with a coupon discount
  Failure/Error: coupon = Stripe::Coupon.create(id: "10PERCENT")
  Stripe::InvalidRequestError:
   Missing required param: duration
  Shared Example Group: "Customer API" called from ./spec/support/stripe_examples.rb:13
  # gems/stripe-1.16.0/lib/stripe.rb:232:in `handle_api_error'
  # gems/stripe-1.16.0/lib/stripe.rb:126:in `rescue in request'
  # gems/stripe-1.16.0/lib/stripe.rb:112:in `request'
  # gems/stripe-1.16.0/lib/stripe/api_operations/create.rb:6:in `create'
  # ./spec/shared_stripe_examples/customer_examples.rb:157:in `block (2 levels) in <top (required)>'
```

Can you add the following to test for this error?

```ruby
it "fails when a coupon is created without a duration" do
  expect { Stripe::Coupon.create(id: "10PERCENT") }.to raise_error {|e|
    expect(e).to be_a(Stripe::InvalidRequestError)
    expect(e.message).to match /duration/
  }
end
```

**Comment by mindeavor** [comment]
Please see the "Live Testing" section [in this wiki page](https://github.com/rebelidealist/stripe-ruby-mock/wiki/Implementing-a-New-Behavior#live-testing) if you want to reproduce the error yourself.

**Comment by jrmyward** [comment]
Big thanks to @alexmamonchik for picking up my slack as I wasn't sure when I would find time to make the updates myself. 

This should be good to go know. Very sorry for the delay and slow response!

**Comment by alexmamonchik** [comment]
@jrmyward your changes applied in #223

**Pull request closed without merging**
