### PR TITLE
Accounts

### PR DESCRIPTION
**Pull request by alexmamonchik**
Accounts support
- part of #55 and #218 
- retrieve default account and all accounts

@mindeavor Account api requires additional actions like registration in Stripe Connect. Only registered users available to create additional accounts or retrieve exists accounts by ID. I think now we have minimal functionality for Account feature - retrieve default account and get all accounts. Another methods (create new, retrieve by id) available for registered in Stripe Connect. I think we should include current code of `accounts` to `master`. Maybe someone or me can add Stripe Connect feature support later. Please comment my code and/or apply this PR.

### CODE REVIEW

**Comment by jeffreyjurgajtis** [comment]
:+1:

**Comment by mindeavor** [comment]
Looks great, thank you!

**Comment by jbourassa** [comment]
@alexmamonchik Yay, we'll get rid of those `WARNING: Unrecognized method + url: [get /v1/account]` in our test logs.

Thank you _very_ much.

**Comment by alexmamonchik** [comment]
@jbourassa I'll fix it asap. But important that now we have basic account functionality!

**Pull request merged**
