### PR TITLE
Add External Accounts

### PR DESCRIPTION
**Pull request by davidstump**
This commit adds the ability to test external accounts for Managed
Accounts. Managed Accounts can have external accounts (very similar to
sources for Customers) that can be either a bank account or a debit
card. These changes include all of the mocks, specs, helpers and logic
needed to start testing these external accounts.

### CODE REVIEW

**Comment by davidstump** [comment]
There had been some previous work done on External Accounts (see: #310), however, there were no request handers and other logic in place to more fully support testing Managed Accounts with external bank accounts.

**Comment by davidstump** [comment]
Hi Alex. Just saw this comment from Jan. Can I confirm that the test account belongs to @mindeavor that needs the adjustment? I re-ran the specs locally and merged with upstream just to make sure nothing seemed off with the initial PR. Thanks :)

**Comment by mindeavor** [comment]
I don't have my account activated, but if someone wants to PM me some test keys on gitter, I can update the test setup to use them.

**Comment by arthurnn** [comment]
so, what is holding this off?

**Comment by Dashue** [comment]
I need this naaaooooo, thanks :)

**Comment by davidstump** [comment]
I believe the hold-up at the moment is the test account that was being used needs to be verified in order to be able to deal with external accounts.

**Comment by Dashue** [comment]
Cheers! Will be looking to utilise this as soon as it's in.

**Comment by davidstump** [comment]
@alexmamonchik Are there any other stripe test accounts that you have used that could be activated?

**Comment by Dashue** [comment]
Words cannot express how much I need this. Maybe reach out to stripe to get sponsored with a dedicated account for this project?

**Comment by alexmamonchik** [comment]
the problem is api version + stripe test keys. So, stripe-ruby-mock follows 2015-09-08 api version. We can't register platform on existing keys because because we don't have access to those accounts. We can change keys to new, but I can create accounts with 2017-02-14 api version - it breaks Recipient feature. I suggest to merge this PR to new branch and new minor version 2.5.0. Also, include #410 to this new 2.5.0 version. What do you think?

**Comment by Dashue** [comment]
I wouldn't be able to comment in regards to #410, sounds like it would be good though?
If there's anything I can chip in with, please let me know.

**Comment by Dashue** [comment]
To be honest, what ever simplest thing that get it's working the fastest. This has been open since oct, and a lot of people would find this functionality useful. I personally don't care if some automated tests aren't working due to problems with api keys. If this won't be sorted I'll probably just pick the changes from this changeset myself to get it working.

**Comment by Dashue** [comment]
As an update to this, I pulled in this PR locally and it worked fine for my tests. We're fine using our own version of stripe-ruby-mock until this gets fixed.

**Comment by borenho** [comment]
@Dashue , @davidstump @alexmamonchik ,  what is the way forward for this feature? I bet many people need this working

**Pull request closed without merging**
